Traceback (most recent call last):
  File "/home/mobase/AAAAAAAAAA/Test_Report_Results_01_07_2025/Report/input/application/main.py", line 216, in <module>
    main()
  File "/home/mobase/AAAAAAAAAA/Test_Report_Results_01_07_2025/Report/input/application/main.py", line 212, in main
    app = UDSApp()
          ^^^^^^^^
  File "/home/mobase/AAAAAAAAAA/Test_Report_Results_01_07_2025/Report/input/application/main.py", line 28, in __init__
    self.initialize_dependencies()
  File "/home/mobase/AAAAAAAAAA/Test_Report_Results_01_07_2025/Report/input/application/main.py", line 51, in initialize_dependencies
    self.config = config_loader.load_config("config.json")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mobase/AAAAAAAAAA/Test_Report_Results_01_07_2025/Report/input/drivers/config_loader.py", line 5, in load_config
    return json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 66 column 5 (char 1249)


------------------
(program exited with code: 1)
Press return to continue
